//
// Created by volt on 12/27/2024.
//




#ifndef LPG_ENGINE_SRC_LPG_ENTITIES_DIRECTIONALLIGHT_HPP_
#define LPG_ENGINE_SRC_LPG_ENTITIES_DIRECTIONALLIGHT_HPP_

#endif //LPG_ENGINE_SRC_LPG_ENTITIES_DIRECTIONALLIGHT_HPP_
