//
// Created by volt on 12/27/2024.
//




#ifndef LPG_ENGINE_SRC_LPG_SYSTEMS_PHYSICSSIMULATIONSYSTEM_HPP_
#define LPG_ENGINE_SRC_LPG_SYSTEMS_PHYSICSSIMULATIONSYSTEM_HPP_

namespace lpg {

    struct PhysicsSimulationSystem {

    };

} // lpg

#endif //LPG_ENGINE_SRC_LPG_SYSTEMS_PHYSICSSIMULATIONSYSTEM_HPP_
